# Generated by Django 4.2.2 on 2023-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('items_purchased', models.TextField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sales',
            name='amount_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='customer_number',
            field=models.FloatField(default=0),
        ),
    ]
