# Generated by Django 4.2.2 on 2023-11-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_remove_salesitems_customer_number_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
