# Generated by Django 4.2.2 on 2024-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_customer_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
